### ISSUE TITLE
Questions on the current implementation

### ISSUE THREAD

**Issue by justinbmeyer** [bitovi/react-pmo#5]
## Todos

- Restaurant order page
- Order history page

**Comment by justinbmeyer** [comment]
## App.js

```js
  const [context, dispatch] = useReducer(contextReducer, {
    currentRestaurant: {},
    getRestaurants: (region, city) => {
      dispatch({
        city,
        region,
        restaurants: null,
        type: "update-restaurants",
      });
    },
    restaurants: {},
    setCurrentRestaurant: (region, city, slug) => {
      dispatch({
        city,
        region,
        slug,
        type: "set-current-restaurant",
      });
    }
  });
```

- [ ] Why empty objects {}, instead of `null`?  
- [ ] Why put these on context?


```jsx
// calling getRestaurants on the context causes a dispatch
    getRestaurants: (region, city) => {
      dispatch({
        city,
        region,
        restaurants: null,
        type: "update-restaurants",
      });
    },

// which then sets the list of restaurants to null ...
case "update-restaurants": {
      const { city, region } = action;
      if (city && region) {
        const { restaurants } = state;
        if (!restaurants[region] || !restaurants[region][city]) {
          const nextRestaurants = { ...restaurants };
          nextRestaurants[region] = { ...restaurants[region] };
          nextRestaurants[region][city] = action.restaurants;
  
          nextState = { ...state, ...{ restaurants: nextRestaurants } };
        }
      }
      break;
    }

// which is essentially spotted ...
// and returns back to update-restaurants
useEffect(() => {
    const { restaurants } = context;
    for (let region in restaurants) {
      for (let city in restaurants[region]) {
        if (restaurants[region][city]) {
          continue;
        }

        console.log(`get restaurants: ${region}, ${city}`);

        getRestaurants(region, city)
          .then(restaurants => {
            dispatch({
              city,
              region,
              restaurants,
              type: "update-restaurants",
            });
          });
      }
    }
  }, [context.restaurants]);
```

- [ ] Why have this in the "app" level? Would all _modeling_ be put here?  _I'd probably suggest keeping App.js just about routing in this training, even if restaurant data can be shared.  Show how to cache in a followup exercise._
- [ ] Pending / resolve state is sort of lost here.  Maybe _undefined_ means not yet loaded, `null` means loading, `Error` means an error, anything else is a return value (`null` can't be a return value then).
- [ ] Does this cause a re-diff on everything each time `contextReducer` is called?
- [ ] Can `getRestaurants: (region, city) => {` not call `dispatch` async?  Couldn't the fetch happen here, then dispatch later?  Wouldn't this avoid needing `useEffect`?  I feel like cycles should be avoided if they can.

**Comment by justinbmeyer** [comment]
## Restaurants.js

```jsx
<select onChange={onRegionChange} value={region}>
                        <option value="">{0 < regions.length ? "Choose a state" : LOADING_MESSAGE}</option>
                        {regions.map(({ name, short }) => (<option key={short} value={short}>{name}</option>))}
                    </select>
```

- [ ] Why `region` and `state` names?


```jsx
            <>
                <option value="">{0 < Object.keys(cities).length ? "Choose a city" : LOADING_MESSAGE}</option>
                {cities && cities[region]
                    ? cities[region].map(({ name }) => (<option key={name} value={name}>{name}</option>))
                    : null
                }
            </>
```
- [ ] Doesn't seem to handle distinquishing between no cities and loading in a correct way


```jsx
                    <select disabled={!region} onChange={onCityChange} value={city}>
                        {cityOptions}
                    </select>
```

- should be disabled if pending 


```jsx
function onRegionChange(evt) {
        setRegion(evt.target.value);
        setCity("");
    }
```

- [ ] Couldn't the `useEffect( ..., [region])` notice the region change and call `setCity` itself?

**Comment by christopherjbaker** [comment]
With the rebuild earlier this year, I don't think any of these questions are relevant anymore. Feel free to re-open if any still are though.
